version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1 -Target CI
test: off
cache:
  - '%USERPROFILE%\.nuget\packages'
  - tools
  - '%USERPROFILE%\.sonar\cache'
